http:
  routers:
    service-a:
      entryPoints:
        - web-a
      rule: PathPrefix(`/`)
      service: service-a
    service-b:
      entryPoints:
        - web-b
      rule: PathPrefix(`/`)
      service: service-b
  services:
    service-a:
      loadBalancer:
        healthCheck:
          path: /actuator/health/readiness
          interval: 1s
          timeout: 500ms
        servers:
        - url: http://service-a-group-1-1:8080
        - url: http://service-a-group-1-2:8080
        - url: http://service-a-group-2-1:8080
        - url: http://service-a-group-2-2:8080
    service-b:
      loadBalancer:
        healthCheck:
          path: /actuator/health/readiness
          interval: 1s
          timeout: 500ms
        servers:
        - url: http://service-b-group-1-1:8080
        - url: http://service-b-group-1-2:8080
        - url: http://service-b-group-2-1:8080
        - url: http://service-b-group-2-2:8080
